feat: spark with airflow

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -46,7 +46,7 @@ x-base-kafka: &base_kafka
   command: "bash -c 'if [ ! -f /tmp/start.sh ]; then echo \"ERROR: Did you forget the start.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/start.sh && /etc/confluent/docker/run ; fi'"
 
 x-spark-worker: &base_spark_worker
-  image: docker.io/bitnami/spark:3.0.1
+  build: ./recommender_system/spark
   restart: on-failure
   volumes:
     - /etc/localtime:/etc/localtime:ro
@@ -64,6 +64,37 @@ x-spark-worker: &base_spark_worker
     - SPARK_RPC_ENCRYPTION_ENABLED=no
     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
     - SPARK_SSL_ENABLED=no
+
+x-grpc: &base_grpc
+  build: ./recommender_system/grpc
+  container_name: recommender_grpc
+  volumes:
+    - ./recommender_system/grpc:/opt/grpc
+  env_file: .env
+
+x-airflow-common: &airflow-common
+  build: ./recommender_system/airflow
+  environment: &airflow-common-env
+    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
+    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-db/${AIRFLOW_DB_NAME}
+    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-db/${AIRFLOW_DB_NAME}
+    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
+    AIRFLOW__CORE__FERNET_KEY: ''
+    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
+    AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
+    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
+  volumes:
+    - ./recommender_system/airflow/fake_data/movies.csv:/opt/metadata/movies.csv
+    - ./recommender_system/airflow/dags:/opt/airflow/dags
+    - ./recommender_system/airflow/src:/opt/airflow/src
+    - ./recommender_system/airflow/logs:/opt/airflow/logs
+  user: "${AIRFLOW_UID:-50000}:0"
+  env_file: .env
+  depends_on: &airflow-common-depends-on
+    redis:
+      condition: service_healthy
+    airflow-db:
+      condition: service_healthy
 
 
 services:
@@ -309,7 +340,7 @@ services:
 
   spark-master:
     <<: *base_service
-    image: docker.io/bitnami/spark:3.0.1
+    build: ./recommender_system/spark
     container_name: spark-master
     hostname: spark-master
     restart: on-failure
@@ -366,32 +397,384 @@ services:
     build: ./recommender_system/jupyter-notebook/
     container_name: jupyter-notebook
     hostname: jupyter-notebook
+    user: root
     depends_on:
       spark-master:
         condition: service_healthy
     volumes:
       - /etc/localtime:/etc/localtime:ro
       - /etc/timezone:/etc/timezone:ro
-      - ./recommender_system/jupyter-notebook/work:/home/developer/work
+      - ./recommender_system/jupyter-notebook/work:/home/jovyan/work
       - ./recommender_system/jupyter-notebook/clickhouse-native-jdbc-shaded-2.6.4.jar:/opt/clickhouse-native-jdbc-shaded-2.6.4.jar
+      - ./recommender_system/jupyter-notebook/mongo-spark-connector_2.12-3.0.1.jar:/opt/mongo-spark-connector_2.12-3.0.1.jar
     profiles:
       - dev_graduate
     ports:
       - ${NOTEBOOK_PORT}:${NOTEBOOK_PORT}
 
-  recommender_grpc:
+  recommender_grpc_dev:
     <<: *base_service
-    build: ./recommender_system/grpc
-    container_name: recommender_grpc
-    volumes:
-      - ./recommender_system/grpc:/opt/grpc
-    env_file: .env
+    <<: *base_grpc
     profiles: 
       - dev_graduate
+    ports:
+      - ${RECOMMENDER_GRPC_PORT}:${RECOMMENDER_GRPC_PORT}
+
+  recommender_grpc:
+    <<: *base_service
+    <<: *base_grpc
+    profiles: 
       - prod
     expose:
       - ${RECOMMENDER_GRPC_PORT}
 
+  mongors1n1:
+    <<: *base_service
+    container_name: mongors1n1
+    image: mongo
+    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
+    expose:
+      - "27017"
+    volumes:
+      - /etc/localtime:/etc/localtime:ro
+      - mongo_cluster1-data1:/data/db
+    profiles: 
+      - dev_graduate
+      - prod
+
+  mongors1n2:
+    <<: *base_service
+    container_name: mongors1n2
+    image: mongo
+    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
+    expose:
+      - "27017"
+    volumes:
+      - /etc/localtime:/etc/localtime:ro
+      - mongo_cluster1-data2:/data/db
+    profiles: 
+      - dev_graduate
+      - prod
+
+  mongors1n3:
+    <<: *base_service
+    container_name: mongors1n3
+    image: mongo
+    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
+    expose:
+      - "27017"
+    volumes:
+      - /etc/localtime:/etc/localtime:ro
+      - mongo_cluster1-data3:/data/db
+    profiles: 
+      - dev_graduate
+      - prod
+
+  mongors2n1:
+    <<: *base_service
+    container_name: mongors2n1
+    image: mongo
+    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
+    expose:
+      - "27017"
+    volumes:
+      - /etc/localtime:/etc/localtime:ro
+      - mongo_cluster1-data4:/data/db
+    profiles: 
+      - dev_graduate
+      - prod
+
+  mongors2n2:
+    <<: *base_service
+    container_name: mongors2n2
+    image: mongo
+    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
+    expose:
+      - "27017"
+    volumes:
+      - /etc/localtime:/etc/localtime:ro
+      - mongo_cluster1-data5:/data/db
+    profiles: 
+      - dev_graduate
+      - prod
+
+  mongors2n3:
+    <<: *base_service
+    container_name: mongors2n3
+    image: mongo
+    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
+    expose:
+      - "27017"
+    volumes:
+      - /etc/localtime:/etc/localtime:ro
+      - mongo_cluster1-data6:/data/db
+    profiles: 
+      - dev_graduate
+      - prod
+
+  mongocfg1:
+    <<: *base_service
+    container_name: mongocfg1
+    image: mongo
+    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
+    expose:
+      - "27017"
+    volumes:
+      - /etc/localtime:/etc/localtime:ro
+      - mongo_cluster1-config1:/data/db
+    profiles: 
+      - dev_graduate
+      - prod
+
+  mongocfg2:
+    <<: *base_service
+    container_name: mongocfg2
+    image: mongo
+    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
+    expose:
+      - "27017"
+    volumes:
+      - /etc/localtime:/etc/localtime:ro
+      - mongo_cluster1-config2:/data/db
+    profiles: 
+      - dev_graduate
+      - prod
+
+  mongocfg3:
+    <<: *base_service
+    container_name: mongocfg3
+    image: mongo
+    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
+    expose:
+      - "27017"
+    volumes:
+      - /etc/localtime:/etc/localtime:ro
+      - mongo_cluster1-config3:/data/db
+    profiles: 
+      - dev_graduate
+      - prod
+
+  mongos1:
+    <<: *base_service
+    container_name: mongos1
+    image: mongo
+    hostname: mongos1
+    depends_on:
+      - mongocfg1
+      - mongocfg2
+      - mongocfg3
+    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017 --bind_ip_all
+    expose:
+      - "27017"
+    volumes:
+      - /etc/localtime:/etc/localtime:ro
+    profiles: 
+      - dev_graduate
+      - prod
+
+  mongos2:
+    <<: *base_service
+    container_name: mongos2
+    image: mongo
+    hostname: mongos2
+    depends_on:
+      - mongocfg1
+      - mongocfg2
+      - mongocfg3
+    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017 --bind_ip_all
+    expose:
+      - "27017"
+    volumes:
+      - /etc/localtime:/etc/localtime:ro
+    profiles: 
+      - dev_graduate
+      - prod
+
+  airflow-db:
+    <<: *base_service
+    image: postgres:13-alpine
+    container_name: airflow-db
+    env_file: .env
+    restart: always
+    environment:
+      - POSTGRES_USER=${AIRFLOW_DB_USER}
+      - POSTGRES_PASSWORD=${AIRFLOW_DB_PASSWORD}
+      - POSTGRES_DB=${AIRFLOW_DB_NAME}
+    profiles: 
+      - dev_graduate
+      - prod
+    volumes:
+      - spark-airflow-db:/var/lib/postgresql/data
+    healthcheck:
+      test: pg_isready -U ${AIRFLOW_DB_USER} -D ${AIRFLOW_DB_NAME} > /dev/null; if [[ $$? == 0 ]]; then echo 0; else echo 1; fi
+      interval: 30s
+      timeout: 10s
+      retries: 5
+
+  airflow-webserver:
+    <<: *base_service
+    <<: *airflow-common
+    container_name: airflow-webserver
+    command: webserver
+    ports:
+      - 8081:8080
+    healthcheck:
+      test: ["CMD", "curl", "--fail", "http://airflow-webserver:8080/health"]
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    restart: always
+    profiles: 
+      - dev_graduate
+      - prod
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
+
+  airflow-scheduler:
+    <<: *base_service
+    <<: *airflow-common
+    container_name: airflow-scheduler
+    command: scheduler
+    healthcheck:
+      test: ['CMD-SHELL', 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    restart: always
+    profiles: 
+      - dev_graduate
+      - prod
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
+
+  airflow-worker:
+    <<: *base_service
+    <<: *airflow-common
+    container_name: airflow-worker
+    command: celery worker
+    healthcheck:
+      test:
+        - 'CMD-SHELL'
+        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    profiles: 
+      - dev_graduate
+      - prod
+    environment:
+      <<: *airflow-common-env
+      DUMB_INIT_SETSID: "0"
+    restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
+
+  airflow-init:
+    <<: *base_service
+    <<: *airflow-common
+    container_name: airflow-init
+    entrypoint: /bin/bash
+    command:
+      - -c
+      - |
+        function ver() {
+          printf "%04d%04d%04d%04d" $${1//./ }
+        }
+        airflow_version=$$(gosu airflow airflow version)
+        airflow_version_comparable=$$(ver $${airflow_version})
+        min_airflow_version=2.2.0
+        min_airflow_version_comparable=$$(ver $${min_airflow_version})
+        if (( airflow_version_comparable < min_airflow_version_comparable )); then
+          echo
+          echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
+          echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
+          echo
+          exit 1
+        fi
+        if [[ -z "${AIRFLOW_UID}" ]]; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
+          echo "If you are on Linux, you SHOULD follow the instructions below to set "
+          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
+          echo "For other operating systems you can get rid of the warning with manually created .env file:"
+          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#setting-the-right-airflow-user"
+          echo
+        fi
+        one_meg=1048576
+        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
+        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
+        disk_available=$$(df / | tail -1 | awk '{print $$4}')
+        warning_resources="false"
+        if (( mem_available < 4000 )) ; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
+          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
+          echo
+          warning_resources="true"
+        fi
+        if (( cpus_available < 2 )); then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
+          echo "At least 2 CPUs recommended. You have $${cpus_available}"
+          echo
+          warning_resources="true"
+        fi
+        if (( disk_available < one_meg * 10 )); then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
+          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
+          echo
+          warning_resources="true"
+        fi
+        if [[ $${warning_resources} == "true" ]]; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
+          echo "Please follow the instructions to increase amount of resources available:"
+          echo "   https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#before-you-begin"
+          echo
+        fi
+        mkdir -p /sources/logs /sources/dags /sources/src
+        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,src}
+        exec /entrypoint airflow version
+    profiles: 
+      - dev_graduate
+      - prod
+    environment:
+      <<: *airflow-common-env
+      _AIRFLOW_DB_UPGRADE: 'true'
+      _AIRFLOW_WWW_USER_CREATE: 'true'
+      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
+      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
+    user: "0:0"
+    volumes:
+      - ./recommender_system/airflow:/sources
+
+  flower:
+    <<: *base_service
+    <<: *airflow-common
+    container_name: airflow-flower
+    command: celery flower
+    ports:
+      - 5555:5555
+    healthcheck:
+      test: ["CMD", "curl", "--fail", "http://flower:5555/"]
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    restart: always
+    profiles: 
+      - dev_graduate
+      - prod
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
 
 networks:
   graduate:
@@ -400,3 +783,13 @@ networks:
 volumes:
   redis-data:
   clickhouse-zookeeper:
+  mongo_cluster1-config1:
+  mongo_cluster1-config2:
+  mongo_cluster1-config3:
+  mongo_cluster1-data1:
+  mongo_cluster1-data2:
+  mongo_cluster1-data3:
+  mongo_cluster1-data4:
+  mongo_cluster1-data5:
+  mongo_cluster1-data6:
+  spark-airflow-db:
